# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-18.04

variables:
  phpVersion: 7.2

steps:
- script: |
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    php -version
  displayName: 'Use PHP version $(phpVersion)'

- script: sudo apt-get install composer
  displayName: 'Install composer'

- script: composer install --no-dev
  displayName: 'Composer dependencies'

- script: mkdir /tmp/phpcsfixer ; composer require --working-dir=/tmp/phpcsfixer friendsofphp/php-cs-fixer ; /tmp/phpcsfixer/vendor/bin/php-cs-fixer fix . --dry-run --diff --rules @PS1,@PSR2,@Symfony
  displayName: 'Linter'

- task: CmdLine@2
  inputs:
    script: |
      for file in `find -name "*.php" -or -name "*.html" -or -name .htaccess | grep -v vendor/ ` ; do
        curl --ftp-create-dirs -u "$(FTPUSER):$(FTPPASS)" -T ${file} ftp://ftpperso.free.fr/web/${file}
      done
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: Temporary upload

# Following fails until https://github.com/microsoft/azure-pipelines-tasks/issues/14676
# is fixed.
- task: FtpUpload@2
  inputs:
    credentialsOption: 'serviceEndpoint'
    serverEndpoint: 'ftpfree'
    rootDirectory: '$(Pipeline.Workspace)'
    filePatterns: |
      **/*.php
      **/*.html
      **/*.htaccess
    remoteDirectory: '/web'
    clean: false
    cleanContents: false
    preservePaths: false
    trustSSL: false
  displayName: 'Publish'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/master'))
